MVCNorthWind2/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCNorthWind2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

MVCNorthWind2/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCNorthWind2.Models;
using System.IO;

namespace MVCNorthWind2.Controllers
{
    public class CategoriesController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // ma teen nüüd käsitsi ühe meetodi - vaata ja kuula, ma ka seletan
        public ActionResult Picture(int? id)
        {
            Category cat = db.Categories.Find(id ?? 0);
            if ((cat?.Picture?.Length??0) == 0) return HttpNotFound();

            var pic = cat.Picture;
            if (pic[0] == 21) pic = pic.Skip(78).ToArray();

            return File(pic, "image/jpg");

        }


        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,CategoryName,Description,Picture")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "CategoryID,CategoryName,Description")] Category category,
            HttpPostedFileBase file
            )
        {
            if (ModelState.IsValid)
            {
                var dbe = db.Entry(category);
                dbe.State = EntityState.Modified;
                // NB! ma PEAN märkima, et pilt ei ole muutunud
                dbe.Property("Picture").IsModified = false;

                if(file != null && file.ContentLength > 0)
                {
                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        category.Picture = buff;
                    }
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCNorthWind2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCNorthWind2.Models;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.Data.Entity.Validation;

namespace MVCNorthWind2.Models
{
    [MetadataType(typeof(ProductMetadata))]
    partial class Product
    {
        public decimal Laoseis => (UnitPrice ?? 0M) * (UnitsInStock ?? 0);
    }

    public class ProductMetadata
    {
        [Display(Name = "Money in stock")]
        [DisplayFormat(DataFormatString = "{0:$0.00}")]
        public decimal Laoseis { get; }

        [Range(1, 200, ErrorMessage = "hind peab olema vahemikus 5 kuni 200")] // validation
        public decimal? UnitPrice { get; set; }
    
    }
}


namespace MVCNorthWind2.Controllers
{
    public class ProductsController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();

        
        

        // GET: Products
        public ActionResult Index
            (
                int size = 0,       // lehe suurus - kui 0, siis kõik
                int page = 1,       // lehe number
                int id = 0,         // CategoryID-filter (kui 0 siis kõik)
                string sort = "ProductId",      // sorteerimisveerg: name, price, units
                string direction = "asc",        // surteerimissuund: asc, desc
                string liiguta = "",    // kas järgmine või eelmine leht
                int editId = 0         // millise toote hinda muuta
            )
        {
            page += (liiguta == "\u2b05" ? -1 : liiguta == "\u27a1" ? 1 : 0);
            
            ViewBag.sort = sort;
            ViewBag.direction = direction;
            ViewBag.size = size;
            ViewBag.page = page;
            ViewBag.editId = editId;
            ViewBag.categoryId = id;


            var products = db.Products
                .Where(x => x.CategoryID == id || id == 0) // see rida
                // ühe tingimusega ja ühe lausega saame 0 korral kõik ja n korral need
                //.Include(p => p.Category)
                ;

            var sortedProduct = products.OrderBy(x => x.ProductID);
            switch((sort+direction).ToLower())
            {
                case "nameasc":
                    sortedProduct = products.OrderBy(x => x.ProductName);
                    break;
                case "namedesc":
                    sortedProduct = products.OrderByDescending(x => x.ProductName);
                    break;
                case "priceasc":
                    sortedProduct = products.OrderBy(x => x.UnitPrice);
                    break;
                case "pricedesc":
                    sortedProduct = products.OrderByDescending(x => x.UnitPrice);
                    break;
                case "unitsasc":
                    sortedProduct = products.OrderBy(x => x.UnitsInStock);
                    break;
                case "unitsdesc":
                    sortedProduct = products.OrderByDescending(x => x.UnitsInStock);
                    break;
            }
            ViewBag.pages = size == 0 ? 0 : sortedProduct.Count() / size;
            if (size == 0) 
                return View(sortedProduct.ToList());
            else 
                return View(sortedProduct.Skip((page - 1) * size).Take(size).ToList());
            // selle saab ka lühemini
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            //if (id == null)
            //{
            //    //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //    return RedirectToAction("Index");
            //}
            Product product = db.Products.Find(id??0);
            if (product == null)
            {
                //return HttpNotFound();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Create
      
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", 7);
            return View(new Product { UnitPrice = 10, CategoryID = 7});
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued,State")] Product product)
        {
            var op = db.Products.Where(x => x.ProductName == product.ProductName).Count();
            if(op > 0)
            {
                ModelState.AddModelError("ProductName", "Sellise nimega toode meil juba on");
            }

            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued,State")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult EditPrice(
                int productId = 0,
                int categoryId = 0,
                decimal UnitPrice = 0,
                int size=0,
                int page=0,
                string sort="",
                string direction=""

            )
        {
            var prod = db.Products.Find(productId);
            if (prod != null)
            {
                try
                {
                    prod.UnitPrice = UnitPrice;
                    db.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    TempData["error"] = e.Message + ": "  + 
                        string.Join(",",
                            e.EntityValidationErrors
                            .Select(x => string.Join(", ", x.ValidationErrors.Select(y => y.ErrorMessage)))) ;
                }
            }
            return RedirectToAction("Index", new { id = categoryId, size=size,page=page,sort=sort,direction=direction });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCNorthWind2/Views/Categories/Create.cshtml
@model MVCNorthWind2.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCNorthWind2/Views/Categories/Delete.cshtml
@model MVCNorthWind2.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCNorthWind2/Views/Categories/Details.cshtml
@model MVCNorthWind2.Models.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>

        </dt>

        <dd>
            <img src="@Url.Action("Picture", new { id = Model.CategoryID })" height="200"/>
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CategoryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@*<h2>Selles kategoorias on:</h2>
<table class="table table-bordered table-hover">
    <tr>
        <th>Toote nimi</th>
        <th>Hind</th>
    </tr>
    @foreach (var p in Model.Products)
    {
        <tr>
            <td>@p.ProductName</td>
            <td>@p.UnitPrice</td>
        </tr>
    }
</table>*@

@Html.Action("Index", "Products", new { id= Model.CategoryID})

@Html.Action("About", "Home");

MVCNorthWind2/Views/Categories/Edit.cshtml
@model MVCNorthWind2.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                <img src="@Url.Action("Picture", new { id = Model.CategoryID })" id="pilt" height="200" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Uus pilt:</label>
            <div class="col-md-10">
                <input type="file" class="form-control" name="file" id="file" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#pilt').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
   $(document).ready(function () {
        $("#file").change(function () {
            readURL(this);
        });
   });
</script>

MVCNorthWind2/Views/Categories/Index.cshtml
@model IEnumerable<MVCNorthWind2.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
           
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            <img src="@Url.Action("Picture", "Categories", new { id = item.CategoryID })" height="80" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CategoryID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CategoryID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CategoryID })
        </td>
    </tr>
}

</table>